export const STELLAR_TOPICS = {
    future: [
        { id: "fut-1", text: "Where in the world will we be 10 years from today?" },
        { id: "fut-2", text: "What's one dream you're afraid to say out loud?" },
        { id: "fut-3", text: "If we retired tomorrow, what would our typical Tuesday look like?" },
        { id: "fut-4", text: "What legacy do you want us to leave behind together?" },
        { id: "fut-5", text: "How do you want our home to feel when we finally live together permanently?" },
        { id: "fut-6", text: "If we could move to any planet together, which one and why?" },
        { id: "fut-7", text: "What is your biggest fear about the future that I can help with?" },
        { id: "fut-8", text: "What's a project you want us to start 5 years from now?" },
        { id: "fut-9", text: "If our future was a book, what would the title of the next chapter be?" },
        { id: "fut-10", text: "What's one thing you want to make sure we never change about us?" },
        { id: "fut-11", text: "In our ideal future, how do we handle being 'old' together?" },
        { id: "fut-12", text: "What is one place we MUST live in for at least a year?" },
        { id: "fut-13", text: "If we wrote a joint memoir 40 years from now, what would be the best story in it?" },
        { id: "fut-14", text: "What is the biggest risk you want us to take together in the next 5 years?" },
        { id: "fut-15", text: "Where do you see us on our 20th anniversary?" }
    ],
    love: [
        { id: "lov-1", text: "What's one thing I do that makes you feel truly seen?" },
        { id: "lov-2", text: "When did you first realize our connection was more than just a crush?" },
        { id: "lov-3", text: "What's your favorite way to be comforted by me?" },
        { id: "lov-4", text: "How has your definition of love changed since we met?" },
        { id: "lov-5", text: "What is the kindest thing I've ever said to you?" },
        { id: "lov-6", text: "Which piece of our 'UZZ' map resonates with you the most?" },
        { id: "lov-7", text: "If you could describe our love in one celestial event, what would it be?" },
        { id: "lov-8", text: "What is a sacrifice you've made for us that I haven't thanked you for enough?" },
        { id: "lov-9", text: "What part of my personality do you think complements yours perfectly?" },
        { id: "lov-10", text: "What's a 'little thing' I do that you've never mentioned you liked?" },
        { id: "lov-11", text: "What was the exact moment you found yourself wanting more than just 'us' as friends?" },
        { id: "lov-12", text: "What is the most vulnerable thing you've ever shared with me?" },
        { id: "lov-13", text: "If you could pick a song that perfectly summarizes our current phase, what is it?" },
        { id: "lov-14", text: "How do I make you feel brave in ways you weren't before?" },
        { id: "lov-15", text: "What is the first thing that comes to mind when you hear my name in a crowded room?" }
    ],
    lust: [
        { id: "lus-1", text: "If we had 24 hours in a secret city, what's one bold thing we'd try?" },
        { id: "lus-2", text: "What's a fantasy you've been shy about sharing?" },
        { id: "lus-3", text: "What's the most attractive thing about my personality?" },
        { id: "lus-4", text: "Where is the wildest place you've ever thought about us being together?" },
        { id: "lus-5", text: "What's a 'look' I give you that instantly makes you feel connected?" },
        { id: "lus-6", text: "What's one thing you want us to explore more in our intimacy?" },
        { id: "lus-7", text: "If we were in a movie, which romantic scene would be 'us'?" },
        { id: "lus-8", text: "What is your absolute favorite physical feature of mine?" },
        { id: "lus-9", text: "What scent reminds you of our most passionate moments?" },
        { id: "lus-10", text: "How can I make you feel more desired than ever before?" },
        { id: "lus-11", text: "What's the most memorable 'stolen moment' we've ever had?" },
        { id: "lus-12", text: "If we were characters in a romance novel, what would our 'chemistry' be described as?" },
        { id: "lus-13", text: "What is your secret favorite physical sensation when we're together?" },
        { id: "lus-14", text: "How has our physical connection evolved since day one?" },
        { id: "lus-15", text: "What's one 'spark' moment from our early days that you still feel today?" }
    ],
    marriage: [
        { id: "mar-1", text: "What's one tradition from your family you want us to carry on?" },
        { id: "mar-2", text: "What does a 'successful' long-term partnership look like to you?" },
        { id: "mar-3", text: "What's your biggest fear about 'forever' and how can we face it?" },
        { id: "mar-4", text: "If we had a wedding, what's the one non-negotiable detail for you?" },
        { id: "mar-5", text: "What does 'home' mean to you in the context of marriage?" },
        { id: "mar-6", text: "How do you want us to handle disagreements when we're together 24/7?" },
        { id: "mar-7", text: "What's one thing your parents did right that you want us to replicate?" },
        { id: "mar-8", text: "What's one thing your parents did that you definitely want to avoid?" },
        { id: "mar-9", text: "If we lived in a different era, how do you think we would have found each other?" },
        { id: "mar-10", text: "What's the most important value you want our partnership to be built on?" },
        { id: "mar-11", text: "How would we define our 'rules of engagement' for conflict resolution?" },
        { id: "mar-12", text: "What does 'fidelity' mean to you in a world full of distractions?" },
        { id: "mar-13", text: "If we had to start over in a new country with nothing, how would we survive together?" },
        { id: "mar-14", text: "What's the one thing about our relationship that you think others would envy?" },
        { id: "mar-15", text: "What is your deepest hope for our life as a married couple?" }
    ],
    kids: [
        { id: "kid-1", text: "If we had a child, which of your traits would you most want them to inherit?" },
        { id: "kid-2", text: "What kind of parent do you think I would be?" },
        { id: "kid-3", text: "How would you want to balance 'us' time and 'family' time?" },
        { id: "kid-4", text: "What’s one lesson you definitely want to teach a next generation?" },
        { id: "kid-5", text: "Would you want to raise kids in a big city or in nature?" },
        { id: "kid-6", text: "How many kids (if any) have you secretly imagined us having?" },
        { id: "kid-7", text: "What's one hobby you'd love to pass down to our children?" },
        { id: "kid-8", text: "What is your biggest fear about parenthood?" },
        { id: "kid-9", text: "How should we handle different parenting styles if they arise?" },
        { id: "kid-10", text: "What is the most beautiful thing about the idea of 'us' as a family?" },
        { id: "kid-11", text: "What kind of stories would we tell our children about how we met?" },
        { id: "kid-12", text: "How would we support a child who was completely different from both of us?" },
        { id: "kid-13", text: "What's the first adventure you'd take a child on?" },
        { id: "kid-14", text: "How would we keep our romance alive while being busy parents?" },
        { id: "kid-15", text: "What family value is non-negotiable for you?" }
    ],
    career: [
        { id: "car-1", text: "How can I better support your professional dreams this year?" },
        { id: "car-2", text: "If you could start any business today, what would it be?" },
        { id: "car-3", text: "Would you ever move across the world for your dream job if I was with you?" },
        { id: "car-4", text: "What’s one work achievement you're proud of that I haven't celebrated enough?" },
        { id: "car-5", text: "What's your biggest 'what if' regarding your career?" },
        { id: "car-6", text: "If money were no object, what would you do every day?" },
        { id: "car-7", text: "How do you want to balance professional success and personal happiness?" },
        { id: "car-8", text: "Who is your biggest professional inspiration and why?" },
        { id: "car-9", text: "What is one skill you've always wanted to learn but haven't had time for?" },
        { id: "car-10", text: "How can we work together to achieve our financial goals?" },
        { id: "car-11", text: "If you could switch careers right now with no risk, what would you do?" },
        { id: "car-12", text: "How do you want us to celebrate each other's professional wins?" },
        { id: "car-13", text: "What's a dream job you had as a kid that you still think about?" },
        { id: "car-14", text: "How can we better integrate our work lives so they don't feel like 'separate' worlds?" },
        { id: "car-15", text: "What is your definition of a 'dream life' versus a 'dream career'?" }
    ],
    plans: [
        { id: "pla-1", text: "What is the very first thing we are doing the next time we see each other?" },
        { id: "pla-2", text: "What’s a trip we haven't talked about yet that we should take?" },
        { id: "pla-3", text: "If we had $10,000 to spend on one weekend, what's the plan?" },
        { id: "pla-4", text: "What's one thing we can start doing weekly to feel closer?" },
        { id: "pla-5", text: "What is your 'dream date' that we haven't gone on yet?" },
        { id: "pla-6", text: "If we could have a weekend with no phones, where would we go?" },
        { id: "pla-7", text: "What's one thing on your 'UZZ' bucket list we should do next month?" },
        { id: "pla-8", text: "If we could invite one person (real or fictional) to dinner, who and why?" },
        { id: "pla-9", text: "What's a new hobby we could start together while being long-distance?" },
        { id: "pla-10", text: "What's the most 'us' thing we can do once we're finally together?" },
        { id: "pla-11", text: "What's a 'surprise' you've always wanted to plan for me by yourself?" },
        { id: "pla-12", text: "If we had a whole month with no responsibilities, where would we go?" },
        { id: "pla-13", text: "What's one thing we can do this weekend to feel like we're in the same room?" },
        { id: "pla-14", text: "What is our 'signature' date night meal?" },
        { id: "pla-15", text: "What's the next big milestone on our shared UZZ map?" }
    ]
};
